DATABASE = 'flaskr.db'
SQL_SCHEMA = 'schema.sql'
DEBUG = True
SECRET_KEY = 'development key'
USERNAME = 'admin'
PASSWORD = 'admin'
FILES_ROOT_DIRECTORY = 'x:/'
#FILES_ROOT_DIRECTORY = 'files'
IGNORED_FILES = ['Thumbs.db']
